/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutPersonImport } from './routes/_layout/person'
import { Route as LayoutPersonPersonImport } from './routes/_layout/person.$person'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonRoute = LayoutPersonImport.update({
  path: '/person',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonPersonRoute = LayoutPersonPersonImport.update({
  path: '/$person',
  getParentRoute: () => LayoutPersonRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/person': {
      id: '/_layout/person'
      path: '/person'
      fullPath: '/person'
      preLoaderRoute: typeof LayoutPersonImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/person/$person': {
      id: '/_layout/person/$person'
      path: '/$person'
      fullPath: '/person/$person'
      preLoaderRoute: typeof LayoutPersonPersonImport
      parentRoute: typeof LayoutPersonImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutPersonRoute: LayoutPersonRoute.addChildren({
      LayoutPersonPersonRoute,
    }),
    LayoutIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/person",
        "/_layout/"
      ]
    },
    "/_layout/person": {
      "filePath": "_layout/person.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/person/$person"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/person/$person": {
      "filePath": "_layout/person.$person.tsx",
      "parent": "/_layout/person"
    }
  }
}
ROUTE_MANIFEST_END */
